name: Lambda 자동 배포

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: AWS 자격증명 설정
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: 변경된 Lambda 함수만 배포
      run: |
        # 변경된 파일 확인
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
        echo "변경된 파일들: $CHANGED_FILES"
        
        # lambda_function.py가 변경되었으면 배포
        if echo "$CHANGED_FILES" | grep -q "lambda_function.py"; then
          echo "lambda_function.py 변경 감지 - 배포 시작"
          zip -r function.zip lambda_function.py
          aws lambda update-function-code \
            --function-name my-test-lambda \
            --zip-file fileb://function.zip
          echo "✅ my-test-lambda 배포 완료!"
        else
          echo "lambda_function.py 변경 없음 - 배포 건너뜀"
        fi
    
    - name: 배포 완료
      run: echo "✅ Lambda 함수 배포 완료!"